
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./_components/navigation";
import { Footer } from "./_components/footer";

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import ReactQueryProvider from "@/utils/reactQuery";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="bg-white min-h-[100dvh] grid grid-rows-[auto_1fr_auto]">
          <ReactQueryProvider>
            <Navigation />
            {children}
            <Footer />
            <ReactQueryDevtools initialIsOpen={false} />
          </ReactQueryProvider>
        </div>
      </body>
    </html>
  );
}
